name: Deploy Release Tag
on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: "./.github/workflows/build.yaml"
    with:
      version: ${{github.ref_name}}
  deploy:
    needs:
      - build
    name: Deploy
    uses: "./.github/workflows/deploy.yaml"
    with:
      version: ${{github.ref_name}}
    secrets: inherit
